FROM java:8
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/company-structure-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} company-structure.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/company-structure.jar"]