version: '3'
services:
  neo4j:
   container_name: neo4j
   image: neo4j:latest
   ports:
    - 7474:7474
    - 7687:7687
   volumes:
    - $HOME/neo4j/neo4j-core1/conf:/conf
    - $HOME/neo4j/neo4j-core1/data:/data
    - $HOME/neo4j/neo4j-core1/logs:/logs
    - $HOME/neo4j/neo4j-core1/plugins:/plugins
   environment:
    - NEO4J_AUTH=neo4j/changeMe
    - NEO4J_dbms_mode=CORE
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_causalClustering_expectedCoreClusterSize=3
    - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
    - NEO4J_dbms_connector_http_listen__address=:7474
    - NEO4J_dbms_connector_https_listen__address=:6477
    - NEO4J_dbms_connector_bolt_listen__address=:7687

  companystructure:
    restart: always
    build: .
    working_dir: /companystructure
    volumes:
      - ./:/companystructure
      - ~/.m2:/root/.m2
    expose:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - neo4j